USE seminar;
DROP TABLE IF EXISTS anwender;

CREATE TABLE anwender(
ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
VORNAME VARCHAR(30),
NACHNAME VARCHAR(30),
GESCHLECHT CHAR(1)
);

INSERT INTO anwender(VORNAME,NACHNAME,GESCHLECHT) VALUES ('KARSTEN','BROTTMAN','D');
INSERT INTO anwender(VORNAME,NACHNAME,GESCHLECHT) VALUES ('MEHO','HUSO','M');
INSERT INTO anwender (VORNAME,GESCHLECHT) VALUES ('Julia','w');


SELECT *
FROM anwender
WHERE NACHNAME IS NULL;


